"""Add price column to baked_goods table

Revision ID: 081fb7254df1
Revises: 1bb55cce6bb7
Create Date: 2023-06-23 09:36:07.042316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081fb7254df1'
down_revision = '1bb55cce6bb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baked_goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baked_goods', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
